#!/bin/sh
LOCALDIR=/home/mw23/R3.14.7/support/positioner
EDMDATAFILES=$EDMDATAFILES:$LOCALDIR/data
export EDMDATAFILES
# export EPICS_CA_SERVER_PORT=6064
# export EPICS_CA_REPEATER_PORT=6065
#
# mp is the device name of the multipositioner
# p1-p8 are the sub-names of the positioners
# 
edm -x -eolc -m mp=BLPOS-OP-COLM-01:MP,p1=:X,p2=:Y,p3=:Z,p4=:OFF pos.edl
